name: 'kubewarden-policy-build-go'
description: 'Build a go policy using go'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  metadata-file:
    description: 'name of the metata file'
    required: false
    default: metadata.yml
  wasm-binary:
    description: 'path to the wasm file to be annotated'
    required: false
    default: policy.wasm
  tinygo-version:
    required: true
    default: 0.26.0
runs:
  using: "composite"
  steps:
    -
      name: Checkout code
      uses: actions/checkout@v3
    -
      name: Install tinygo
      shell: bash
      run: |
        wget https://github.com/tinygo-org/tinygo/releases/download/v${{ inputs.tinygo-version }}/tinygo_${{ inputs.tinygo-version }}_amd64.deb
        sudo dpkg -i tinygo_${{ inputs.tinygo-version }}_amd64.deb
    -
      name: Build Wasm module
      shell: bash
      run: |
        tinygo build -o ${{ inputs.wasm-binary }} -target=wasi -no-debug .
    -
      name: Generate the SBOM files
      shell: bash
      run: |
        spdx-sbom-generator -f json

        # SBOM files should have "sbom" in the name due the CLO monitor
        # https://clomonitor.io/docs/topics/checks/#software-bill-of-materials-sbom
        mv bom-go-mod.json policy-sbom.spdx.json
    -
      name: Annotate Wasm module
      shell: bash
      run: |
        kwctl annotate -m ${{ inputs.metadata-file }} -o annotated-policy.wasm ${{ inputs.wasm-binary }}
    -
      name: Sign BOM file
      shell: bash
      run: |
        cosign sign-blob --output-certificate policy-sbom.spdx.cert \
          --output-signature policy-sbom.spdx.sig \
          policy-sbom.spdx.json
      env:
        COSIGN_EXPERIMENTAL: 1
    -
      name:  Upload policy SBOM files
      uses: actions/upload-artifact@v3
      with:
        name: policy-sbom
        path: |
          policy-sbom.spdx.json
          policy-sbom.spdx.cert
          policy-sbom.spdx.sig
