name: Build and release a Kubewarden policy written in Swift

on:
  workflow_call:
    inputs:
      oci-target:
        type: string
        required: true
      artifacthub:
        description: 'check artifacthub-pkg.yml for submission to ArtifactHub'
        required: false
        type: boolean
        default: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@v2
      -
        uses: actions/checkout@v3
        with:
          # until https://github.com/actions/checkout/pull/579 is released
          fetch-depth: 0
      -
        id: calculate-version
        if: ${{ inputs.artifacthub }}
        # obtain latest tag. Here it must be the current release tag
        run: echo "version=$(git describe --tags --abbrev=0 | cut -c2-)" >> $GITHUB_OUTPUT
        shell: bash
      -
        name: Check that artifacthub-pkg.yml is up-to-date
        if: ${{ inputs.artifacthub }}
        uses: kubewarden/github-actions/check-artifacthub@v2
        with:
          version: ${{ steps.calculate-version.outputs.version }}
      -
        name: install wasm-strip
        run: |
          export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
          sudo apt-get -q update
          sudo apt-get -q install -y wabt binaryen
      -
        name: Build release
        uses: swiftwasm/swiftwasm-action@v5.7
        with:
          shell-action: swift build -c release --triple wasm32-unknown-wasi --build-path build
      -
        name: optimize policy
        run: |
          # need to fix file permissions because of some issue with Swift Foundation and filesystem
          sudo chmod 777 build/wasm32-unknown-wasi/release/Policy.wasm
          wasm-strip build/wasm32-unknown-wasi/release/Policy.wasm
          wasm-opt -Os build/wasm32-unknown-wasi/release/Policy.wasm -o policy.wasm

      -
        name: Annotate Wasm module
        run: |
          kwctl annotate -m metadata.yml -o annotated-policy.wasm policy.wasm
      -
        name: Run e2e tests
        run: |
          make e2e-tests
      -
        name: Release
        uses: kubewarden/github-actions/policy-release@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          oci-target: ${{ inputs.oci-target }}
