name: Tests and linters

on:
  workflow_call:
    inputs:
      artifacthub:
        description: 'check artifacthub-pkg.yml for submission to ArtifactHub'
        required: false
        type: boolean
        default: true
    secrets: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - name: run Go unit tests
        run: make test
  check-artifacthub:
    if: ${{ inputs.artifacthub }}
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
        with:
          # until https://github.com/actions/checkout/pull/579 is released
          fetch-depth: 0
      -
        name: Install kwctl
        uses: kubewarden/github-actions/kwctl-installer@v2
      -
        id: calculate-version
        run: echo "version=$(git describe --tags --abbrev=0 | cut -c2-)" >> $GITHUB_OUTPUT
        shell: bash
      -
        name: Check that artifacthub-pkg.yml is up-to-date
        uses: kubewarden/github-actions/check-artifacthub@v2
        with:
          version: ${{ steps.calculate-version.outputs.version }}
          check_version: false # must match a git tag that hasn't been created yet, so let's ignore until then
