name: Build and release a Kubewarden policy written in Rego

on:
  workflow_call:
    inputs:
      oci-target:
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@v2
      -
        name: Install opa
        uses: kubewarden/github-actions/opa-installer@v2
      -
        uses: actions/checkout@v3
      -
        name: Build policy
        run: |
          make policy.wasm
      -
        name: Annotate policy
        run: |
          make annotated-policy.wasm
      -
        name: Run e2e tests
        run: |
          make e2e-tests
      -
        name: Release
        uses: kubewarden/github-actions/policy-release@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          oci-target: ${{ inputs.oci-target }}
